# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a27268f8dbbc044ae6f5c2965800e5c9a3e3f3523633c5b1bb8b158e92448d8c67a7dda3e38a7dfd7321ce73115a42af9f7fdaed1d5a05a10fe73ab60b7ae7e6

test:
  secret_key_base: b6dc93d2708d3291a9ec6ca4cbcf9159fd06d48a151d9f5c80637ec18e7d85276bcb55b2d9028ecfcff776ee09812fbbf8dfb25ecd426ddb527c35091cdfc8ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
